### ISSUE TITLE
ListenDICOM is missing a @TriggerSerially annotation on the onTrigger() method.

### ISSUE THREAD

**Issue by henrikjohansen** [blezek/nifi-dicom#20]
The `ListenDICOM` processor is not safe for concurrent execution and should be marked as such.

Currently, you can configure > 1 'Concurrent Threads' in the processors configuration :
![screenshot-103120241527](https://github.com/user-attachments/assets/1cc6ba78-0375-4f1f-a847-a83d4ef00782)

... but doing so leads to `java.net.BindException: Address already in use` errors.

Setting the aforementioned annotation marks the 'Concurrent Threads' field as read-only and sets it's value to `1`.

**Comment by blezek** [comment]
Completed, see https://github.com/blezek/nifi-dicom/releases/tag/v1.27.3
