### ISSUE TITLE
ModifyDICOMTags leaves temporary files behind

### ISSUE THREAD

**Issue by henrikjohansen** [blezek/nifi-dicom#21]
The `ModifyDICOMTags` processor leaves temporary files behind in `/tmp` - for each` .dcm` file the processor handles it creates a file in `/tmp` following a similar naming strategy (`blkxxxxxxxxxxxxx.tmp`).

IIRC this has always been the case - at least I could reproduce this behaviour with multiple versions of `nifi-dicom`, including the most recent version (`2.0.0-M4`).

This has some undesirable consequences, such as machines running out of diskspace.

Ideally, the processor should clean up after itself :)

**Comment by blezek** [comment]
Thanks for the catch, I'll fix it now.
